# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_de_pago', models.CharField(max_length=50)),
            ],
        ),
    ]
