# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0002_calendario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='calendario',
            new_name='calendario_escolar',
        ),
    ]
