# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0002_formadepago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formadepago',
            options={'verbose_name_plural': 'Formas de pago'},
        ),
    ]
