# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0003_auto_20180309_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contrasena',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
