# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0007_auto_20181216_2242'),
        ('siad', '0004_auto_20181216_2237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendario',
        ),
    ]
