# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0004_empleado_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
            },
        ),
    ]
