# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0005_delete_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendario', models.CharField(max_length=50)),
            ],
        ),
    ]
