# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siad', '0001_initial'),
        ('controlescolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgresoGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_de_recibo', models.IntegerField(help_text='Ingresa el folio del recibo de cotejo')),
                ('concepto', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('factura', models.CharField(max_length=30)),
                ('proxima_fecha_de_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto_futuro_a_cubrir', models.DecimalField(decimal_places=2, max_digits=7)),
                ('movimiento_verificado_por_direccion', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Egresos generales',
            },
        ),
        migrations.CreateModel(
            name='EgresoNomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_de_recibo', models.IntegerField()),
                ('concepto', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proxima_fecha_de_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto_futuro_a_cubrir', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pago_hecho_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Egresos nominas',
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PagosAlumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('concepto', models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Colegiatura', 'Colegiatura'), ('Quincenal', 'Quincenal')], default='Colegiatura', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('folio', models.CharField(default='0000', max_length=10)),
                ('cancelado', models.BooleanField(default=False, help_text='Si un pago es cancelado activa esta casilla')),
                ('movimiento_verificado_por_direccion', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante')),
                ('forma_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.FormaDePago')),
            ],
            options={
                'verbose_name_plural': 'Pagos de alumnos',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=20)),
                ('calle', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('ciudad_y_estado', models.CharField(max_length=100)),
                ('cp', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=50)),
                ('telefono_extension', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Tarjeton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha a partir de la cual se programaran los siguientes pagos')),
                ('descripcion', models.CharField(default='Creacion: 2018-08-10 17:28', help_text='Descripcion breve relativa al tarjeton', max_length=100)),
                ('esquema_de_pago', models.CharField(choices=[('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Un solo pago', 'Un solo pago'), ('Otro', 'Otro')], default='Semanal', help_text='Esquema de pago', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Aqui ingresa el monto total del servicio', max_digits=7)),
                ('pago_periodico', models.DecimalField(decimal_places=2, help_text='Cuanto pagara en cada semana, quincena o mes', max_digits=7)),
                ('monto_cubierto', models.BooleanField(default=False, help_text='Activa esta casilla si el alumno ha cubierto la totalidad del monto')),
                ('proxima_fecha_de_pago', models.DateField(default=django.utils.timezone.now)),
                ('pagos_atrasados', models.IntegerField(default=0)),
                ('tarjeton_verificado_por_direccion', models.BooleanField(default=False)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante')),
                ('pagos', models.ManyToManyField(blank=True, help_text='Estos son los pagos que ha realizado el alumno', to='contabilidad.PagosAlumno')),
            ],
            options={
                'verbose_name_plural': 'Tarjetones',
            },
        ),
        migrations.AddField(
            model_name='egresogenerales',
            name='pago_hecho_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.Proveedor'),
        ),
        migrations.AddField(
            model_name='egresogenerales',
            name='realizo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado'),
        ),
    ]
