# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-08-10 17:29', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
