# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0001_initial'),
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosalumno',
            name='curso_a_pagar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Curso'),
            preserve_default=False,
        ),
    ]
