# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_auto_20180810_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(default='Creacion: 2018-09-13 01:56', help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Aqui ingresa el monto que se cubrira en pagos', max_digits=7),
        ),
    ]
