# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-05 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_pagosalumno_curso_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosalumno',
            name='fecha_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
