# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20170805_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egreso',
            old_name='numero_registro',
            new_name='folio_de_recibo',
        ),
        migrations.RenameField(
            model_name='egreso',
            old_name='destino',
            new_name='pago_hecho_a',
        ),
        migrations.AddField(
            model_name='egreso',
            name='proxima_fecha_de_pago',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='concepto',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='factura',
            field=models.CharField(choices=[('Nomina', 'Nomina'), ('Servicios generales', 'Servicios generales (cfe,internet,etc)'), ('Gastos corrientes', 'Gastos corrientes (copias, papeleria, ferreteria)'), ('Otros', 'Otros')], max_length=30),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
