# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_auto_20180912_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeton',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=7000, help_text='Aqui ingresa el monto total del servicio', max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(default='Creacion: 2018-09-13 02:03', help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
    ]
