# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-13 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20171213_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='monto_futuro_a_cubrir',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='egreso',
            name='factura',
            field=models.CharField(max_length=30),
        ),
    ]
