# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-13 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_auto_20180912_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeton',
            old_name='monto',
            new_name='monto_a_pagos',
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(default='Creacion: 2018-09-13 02:04', help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
    ]
