# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-14 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0001_initial'),
        ('contabilidad', '0005_auto_20171213_0333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso_nomina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_de_recibo', models.IntegerField()),
                ('concepto', models.CharField(max_length=40)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('proxima_fecha_de_pago', models.DateField(default=django.utils.timezone.now)),
                ('monto_futuro_a_cubrir', models.DecimalField(decimal_places=2, max_digits=7)),
                ('pago_hecho_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado')),
            ],
        ),
    ]
