# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-17 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_auto_20180912_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosalumno',
            name='bonificacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aqui ingresa la bonificacion que se le hara al alumno', max_digits=7),
        ),
        migrations.AlterField(
            model_name='pagosalumno',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Aqui ingresa el monto efectivo que el alumno paga a la institucion', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(default='Creacion: 2018-09-17 13:42', help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='inicio',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha del primer pago programado'),
        ),
    ]
