# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0001_initial'),
        ('contabilidad', '0006_egreso_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='movimiento_verificado_por_direccion',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egreso',
            name='realizo_pago',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado'),
            preserve_default=False,
        ),
    ]
