# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0001_initial'),
        ('contabilidad', '0008_auto_20171219_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha a partir de la cual se programaran los siguientes pagos')),
                ('Esquema_de_pago', models.CharField(choices=[('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Un solo pago', 'Un solo pago'), ('Otro', 'otro')], default='Semanal', help_text='Esquema de pago', max_length=10)),
                ('monto_cubierto', models.BooleanField(default=False, help_text='Activa esta casilla si el alumno ha cubierto la totalidad del monto')),
                ('alumno', models.ForeignKey(help_text='Id del alumno al que pertenece este tarjeton', on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='pagosalumno',
            name='curso_a_pagar',
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='alumno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='egresogenerales',
            name='folio_de_recibo',
            field=models.IntegerField(help_text='Ingresa el folio del recibo de cotejo'),
        ),
        migrations.AlterField(
            model_name='egresogenerales',
            name='movimiento_verificado_por_direccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarjeton',
            name='pagos',
            field=models.ManyToManyField(help_text='Estos son los pagos que ha realizado el alumno', to='contabilidad.PagosAlumno'),
        ),
    ]
