# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 03:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_auto_20171226_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeton',
            name='alumno',
        ),
    ]
