# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0001_initial'),
        ('contabilidad', '0010_remove_tarjeton_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeton',
            name='alumno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
            preserve_default=False,
        ),
    ]
