# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_tarjeton_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeton',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='Esquema_de_pago',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Un solo pago', 'Un solo pago'), ('Otro', 'Otro')], default='Semanal', help_text='Esquema de pago', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='pagos',
            field=models.ManyToManyField(blank=True, help_text='Estos son los pagos que ha realizado el alumno', to='contabilidad.PagosAlumno'),
        ),
    ]
