# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_auto_20180102_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
        ),
    ]
