# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-07 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0013_auto_20180103_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='egresogenerales',
            options={'verbose_name_plural': 'Egresos generales'},
        ),
        migrations.AlterModelOptions(
            name='egresonomina',
            options={'verbose_name_plural': 'Egresos nominas'},
        ),
        migrations.AlterModelOptions(
            name='pagosalumno',
            options={'verbose_name_plural': 'Pagos de alumnos'},
        ),
        migrations.AlterModelOptions(
            name='tarjeton',
            options={'verbose_name_plural': 'Tarjetones'},
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='forma_de_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Deposito', 'Deposito'), ('Transferencia', 'Transferencia'), ('Cheque', 'Cheque'), ('Otro', 'Otro')], default='Semanal', help_text='Esquema de pago', max_length=10),
        ),
    ]
