# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0016_auto_20181216_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeton',
            name='deuda_actual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Esta es la cantidad de dinero que debe actualmente', max_digits=7),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(default='Creacion: 2018-12-18 14:59', help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
    ]
