# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_auto_20181218_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.TextField(help_text='Descripcion breve relativa al tarjeton', max_length=200),
        ),
    ]
