# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0017_auto_20180309_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: <function now at 0x7fc0bee687b8>', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
