# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0018_auto_20180309_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosalumno',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.FormaDePago'),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: <function now at 0x7f929b42e7b8>', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
