# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0019_auto_20181219_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortecaja',
            name='fecha_inicio',
        ),
        migrations.AlterField(
            model_name='pagosalumno',
            name='concepto',
            field=models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Colegiatura', 'Colegiatura'), ('Cargo administrativo', 'Cargo administrativo')], default='Colegiatura', max_length=20),
        ),
    ]
