# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0003_auto_20180309_2057'),
        ('contabilidad', '0019_auto_20180309_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosalumno',
            name='concepto',
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='concepto1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='siad.FormaDePago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: <function now at 0x7fe43f2247b8>', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
