# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0020_auto_20181221_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortecaja',
            name='fecha_fin',
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='fecha_de_corte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
