# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0003_auto_20180309_2057'),
        ('contabilidad', '0020_auto_20180309_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagosalumno',
            name='concepto1',
        ),
        migrations.RemoveField(
            model_name='pagosalumno',
            name='forma_de_pago',
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='concepto',
            field=models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Colegiatura', 'Colegiatura')], default='Colegiatura', max_length=20),
        ),
        migrations.AddField(
            model_name='pagosalumno',
            name='forma_de_pago1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='siad.FormaDePago'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: <function now at 0x7f238c02c7b8>', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
