# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_auto_20180309_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeton',
            name='movimiento_verificado_por_direccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: <function now at 0x7f041f2b37b8>', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
