# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0021_auto_20181221_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cortecaja',
            name='fecha_de_corte',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
