# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0022_auto_20181221_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortecaja',
            name='monto_recibido',
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='egresos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de los egresos', max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cortecaja',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma total de los ingresos', max_digits=7),
            preserve_default=False,
        ),
    ]
