# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0023_auto_20180309_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosalumno',
            name='folio',
            field=models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Colegiatura', 'Colegiatura')], default='0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-03-17 06:16', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
