# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0024_auto_20180317_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-03-21 00:10', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
