# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0025_auto_20180320_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-04-08 00:51', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
