# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0026_auto_20180407_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagosalumno',
            old_name='forma_de_pago1',
            new_name='forma_de_pago',
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-05-16 12:31', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
