# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-10 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0007_auto_20181219_0832'),
        ('contabilidad', '0026_auto_20190806_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('concepto', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('folio', models.CharField(default='0000', max_length=10)),
                ('forma_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.FormaDePago')),
            ],
            options={
                'verbose_name_plural': 'Ingresos generales',
            },
        ),
    ]
