# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0027_auto_20180516_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-05-16 13:32', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
