# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0028_auto_20180516_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosalumno',
            name='folio',
            field=models.CharField(default='0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-05-20 14:50', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
