# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0034_auto_20180524_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagosalumno',
            name='concepto',
            field=models.CharField(choices=[('Inscripcion', 'Inscripcion'), ('Colegiatura', 'Colegiatura'), ('Quincenal', 'Quincenal')], default='Colegiatura', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarjeton',
            name='descripcion',
            field=models.CharField(default='Creacion: 2018-06-13 13:44', help_text='Descripcion breve relativa al tarjeton', max_length=100),
        ),
    ]
