# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-10 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('creacion_de_registro', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=60)),
                ('telefono', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=13)),
                ('lugar_de_residencia', models.CharField(default='Guanajuato', help_text='Ingresa el estado en el cual reside el aspirante', max_length=20)),
                ('forma_contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.FormaContacto')),
                ('plantel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel')),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Empleado')),
            ],
            options={
                'verbose_name_plural': 'Prospectos',
            },
        ),
    ]
