# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0004_empleado_contrasena'),
        ('promotoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantes',
            name='lugar_de_residencia',
            field=models.CharField(default='Guanajuato', help_text='Ingresa el estado en el cual reside el aspirante', max_length=20),
        ),
        migrations.AddField(
            model_name='aspirantes',
            name='plantel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
    ]
