# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotoria', '0002_auto_20180320_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirantes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
