# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siad', '0001_initial'),
        ('promotoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_curso', models.DecimalField(decimal_places=2, max_digits=7)),
                ('adeudo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_de_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_de_termino', models.DateField(default=django.utils.timezone.now)),
                ('boleta', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentacion_completa', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Documentacion',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_registro', models.DateField(default=django.utils.timezone.now)),
                ('numero_de_control', models.IntegerField(null=True)),
                ('curp', models.CharField(max_length=20, null=True)),
                ('calle', models.CharField(max_length=100, null=True)),
                ('colonia', models.CharField(max_length=100, null=True)),
                ('entre_calles', models.CharField(max_length=100, null=True)),
                ('cp', models.CharField(max_length=5, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('grad_estudios', models.CharField(max_length=50, null=True)),
                ('estado_civil', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('numero_de_hijos', models.IntegerField(null=True)),
                ('Aspirante', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='promotoria.Aspirantes')),
                ('cursos', models.ManyToManyField(to='controlescolar.Curso')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Empresa')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Estatus')),
                ('plantel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='documentacion',
            name='alumno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Estudiante'),
        ),
        migrations.AddField(
            model_name='documentacion',
            name='documentacion_entregada',
            field=models.ManyToManyField(to='siad.Documento'),
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(to='controlescolar.Materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_de_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siad.Servicio'),
        ),
    ]
