# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-29 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='adeudo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='costo_curso',
        ),
    ]
