# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-10 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0002_auto_20171229_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contrasena',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(default='0', max_length=20, null=True),
        ),
    ]
