# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-05 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0001_initial'),
        ('controlescolar', '0002_estudiante_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='plantel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Plantel'),
        ),
    ]
