# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0003_auto_20180309_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='entre_calles',
        ),
    ]
