# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-08 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0004_remove_estudiante_entre_calles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='grad_estudios',
            new_name='grado_estudios',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cursos',
            field=models.ManyToManyField(blank=True, null=True, to='controlescolar.Curso'),
        ),
    ]
