# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0005_horario'),
        ('controlescolar', '0005_auto_20180407_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Horario'),
        ),
    ]
