# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siad', '0004_auto_20181216_2237'),
        ('controlescolar', '0006_auto_20181216_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='calendario',
        ),
        migrations.AddField(
            model_name='materia',
            name='plantel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Empresa'),
        ),
    ]
