# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0006_curso_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='cursos',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cursos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Curso'),
        ),
    ]
