# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-20 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0007_auto_20180520_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='cursos',
            new_name='curso',
        ),
    ]
