# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0008_auto_20180520_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(blank=True, to='controlescolar.Materia'),
        ),
    ]
