# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-17 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0008_auto_20181216_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='plantel',
            new_name='calendario',
        ),
    ]
