# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-02 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0009_auto_20180524_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='clave_de_la_materia',
            field=models.CharField(default='0000', help_text='Ingresa aqui la clave de la materia', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='numero_de_preguntas',
            field=models.IntegerField(default=0, help_text='Numero de preguntas del examen de la materia', null=True),
        ),
    ]
