# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0010_auto_20180701_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='clave_de_la_materia',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='numero_de_preguntas',
        ),
    ]
