# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-19 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0010_auto_20181219_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='siad.Estatus'),
        ),
    ]
