# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-06 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlescolar', '0011_auto_20180706_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_examen', models.CharField(max_length=60)),
                ('clave_del_examen', models.CharField(max_length=4, null=True)),
                ('numero_de_reactivos', models.IntegerField(default=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='examen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controlescolar.Catalogo'),
        ),
    ]
